### ISSUE TITLE
bug: alt + tab, will not trigger keyup event

### ISSUE THREAD

**Issue by ohhowang** [stevenlei/spacingjs#10]
![image](https://raw.githubusercontent.com/oh-mine/Blog-Images/master/ezgif-7-26fbcd9c4800.gif)

**Comment by stevenlei** [comment]
This is a known issue caused by the limitation of browser:
https://stackoverflow.com/questions/40434142/javascript-event-preventdefault-is-useless-for-alttab-in-windows
