### ISSUE TITLE
support for elements in shadow dom

### ISSUE THREAD

**Issue by hliang** [stevenlei/spacingjs#11]
Looks like it is unable to inspect the elements in shadow DOM of web component.
For example on [lit.dev](https://lit.dev/playground/), there are custom html elements `playground-file-editor` and `resize-bar`, spacingjs can inspect the custom element, but not the elements encapsulated inside.

**Comment by dxsun97** [comment]
> Looks like it is unable to inspect the elements in shadow DOM of web component. For example on [lit.dev](https://lit.dev/playground/), there are custom html elements `playground-file-editor` and `resize-bar`, spacingjs can inspect the custom element, but not the elements encapsulated inside.

It works now, I submitted a pull request a few days ago
