### ISSUE TITLE
能否出一个查看字体、字号、描边色、填充色的版本呢？

### ISSUE THREAD

**Issue by LLLvJunnn** [stevenlei/spacingjs#25]

**Comment by Xavier9896** [comment]
😳试着加了下，emmm……一言难尽
![image](https://user-images.githubusercontent.com/34981520/234201488-badad2d4-795d-41f4-8f3a-29d474f1cfd3.png)
还是审查元素吧😂
![image](https://user-images.githubusercontent.com/34981520/234201743-e7005da0-5850-446e-9595-0d17b8ceeb81.png)

**Comment by stevenlei** [comment]
Just merged an update from a PR, which supports displaying font-size now.

We can consider a better way to display more infos.
