### ISSUE TITLE
Use spacingjs as a chrome extension

### ISSUE THREAD

**Issue by mivinci** [stevenlei/spacingjs#3]
Hi, Steven. Thanks for making spacingjs! Is it worth making it a chrome extension so that it can be used in any website just by a click on the browser?

**Comment by eggx8** [comment]
May be first make a `tampermonkey` script for now and then create a more beautiful chrome extension.
I can help with that.

**Comment by stevenlei** [comment]
Thanks for your suggestion, maybe we can create a Chrome extension and what it do is just load the script to the website on the active tab? I didn't check the documentation yet, will do. :)

**Comment by LavaCxx** [comment]
just save it as a bookmark.
`javascript:(function()%7Bfetch(%22https%3A%2F%2Funpkg.com%2Fspacingjs%22).then(async%20(res)%20%3D%3E%20eval(await%20res.text()))%7D)()`

**Comment by eggx8** [comment]
Temporary [Tampermonkey Script](https://greasyfork.org/zh-CN/scripts/435347-spacing-js) without minify.

**Comment by ohhowang** [comment]
This is a chrome extension demo and it works.
[https://github.com/oh-mine/spacingjs-extension](https://github.com/oh-mine/spacingjs-extension)

**Comment by mivinci** [comment]
> This is a chrome extension demo and it works. https://github.com/oh-mine/spacingjs-extension

@oh-mine Yeah I've made a PR that has the same solution as yours. Maybe a PR is a bad idea. We just need in README a link to repos of spacingjs extensions. @stevenlei

**Comment by stevenlei** [comment]
Thanks both @oh-mine @Mivinci for your great work! I am going to merge into this Repo as we might have more features later on.

**Comment by thetbw** [comment]
Just copy dist/bundle.js to tampermonkey like this
![](https://i.loli.net/2021/11/12/opOLxADGyu6TndS.png)

**Comment by PaulChess** [comment]
Oh, when I experienced `spacingjs`, my first idea is integrating it to a chrome extension too. But it seems that I made 
repetitive work when saw the issue.  
Anyway, I also paste my work in this issue hah: https://github.com/PaulChess/SpacingChromePlugin

**Comment by stevenlei** [comment]
It is available on the [Chrome web store](https://chrome.google.com/webstore/detail/spacingjs/fhjegjndanjcamfldhenjnhnjheecgcc) now. Thanks all.
