### ISSUE TITLE
Windows下按下截屏键后再按Alt选择元素后会出现bug

### ISSUE THREAD

**Issue by misaka10843** [stevenlei/spacingjs#4]
首先非常感谢steven老师写的这一个js qwq
但是本人发现似乎按下win+Shift+S（截屏快捷键）后再按Alt键选择元素后，
关闭/完成截屏后会出现无需按下Alt也能选择其他元素，
并且重新按下Alt关闭后就不能再使用了，必须刷新页面才能重新使用

请问如何解决此问题qwq

https://user-images.githubusercontent.com/69132853/141216640-3e68095c-3add-46f7-919c-557374c123ac.mp4

**Comment by flyingff** [comment]
It seems not enough only listening to keyup event.
Maybe checking `e.altKey` in 'mousemove' event helps.

**Comment by stevenlei** [comment]
Thanks, this should be the issue with the `window` get blurred (lost the focus) so that the event listener not working properly after that. I will check. Thanks

**Comment by stevenlei** [comment]
Hold down with the `Shift` key will delay the dismiss of measurement results now, available on the latest version `1.0.7`.
