### ISSUE TITLE
Support for mobile mode

### ISSUE THREAD

**Issue by flyingff** [stevenlei/spacingjs#5]
I tried to inspect mobile page on desktop Chrome, but the behavior does not follow my intuition. 

I need to tap an element, press down alt key, then tap the other element. 

IMHO, If it can support "locking" element on first tap, then display distance with subsequent tapped element, it will be more helpful.

**Comment by stevenlei** [comment]
Might be because of simulating mobile device on Chrome actually listen to the `touch` events, so that we should handle `touch` event also instead of `mouse` only. Thanks.
