### ISSUE TITLE
Display more element information

### ISSUE THREAD

**Issue by flyingff** [stevenlei/spacingjs#6]
Maybe we can display element `width`, `height`, and some more information in first hover element? 

A little like chrome devtool's inspect behavior.

**Comment by stevenlei** [comment]
Agree, `width` and `height` should be added. Can also consider showing `class` list. `padding` and `margin` might be a bit difficult, let's see.

**Comment by stevenlei** [comment]
`width` and `height` have been added, if we want to show more information, let's discuss in a separate thread.
