### ISSUE TITLE
Use preact or other view layer library

### ISSUE THREAD

**Issue by flyingff** [stevenlei/spacingjs#7]
Using declarative view makes the app more predictable and easy to maintain.

Since you have had webpack, it's not hard to add support for it.

**Comment by stevenlei** [comment]
May I know more about this? Thanks

**Comment by flyingff** [comment]
Official site: https://preactjs.com/

It uses jsx and react-like api, but in a small bundle. Just declaring DOM structure you want to build, then it will handle other things.

I searched for a simple minimal example: https://github.com/aganglada/preact-minimal

**Comment by stevenlei** [comment]
Picking up the project lately, will consider to support React first. Thank you.
